// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package sqlc

import (
	"context"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (topic) VALUES (?)
RETURNING id, topic
`

func (q *Queries) CreateRoom(ctx context.Context, topic string) (Room, error) {
	row := q.db.QueryRowContext(ctx, createRoom, topic)
	var i Room
	err := row.Scan(&i.ID, &i.Topic)
	return i, err
}

const getRoom = `-- name: GetRoom :one
SELECT id, topic FROM rooms
WHERE id = ?
`

func (q *Queries) GetRoom(ctx context.Context, id int64) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoom, id)
	var i Room
	err := row.Scan(&i.ID, &i.Topic)
	return i, err
}

const listRooms = `-- name: ListRooms :many
SELECT id, topic FROM rooms
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(&i.ID, &i.Topic); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
